### ISSUE TITLE
KeyError: 'O' in training

### ISSUE THREAD

**Issue by vasilikivmo** [Hironsan/anago#43]
Hello, I added my custom datasets in the same format as your examples. (Tab delimited Entity and Label, if exists).
Just before when the first epoch is about to end, the scripts crushes, with an error show below:

Traceback (most recent call last):

  File "<ipython-input-6-dcc1d1e249c3>", line 1, in <module>
    model.train(x_train, y_train, x_valid, y_valid)

  File "anago/wrapper.py", line 50, in train
    trainer.train(x_train, y_train, x_valid, y_valid)

  File "anago/trainer.py", line 51, in train
    callbacks=callbacks)

  File "/opt/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 2262, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)

  File "/opt/anaconda2/lib/python2.7/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)

  File "anago/metrics.py", line 124, in on_epoch_end
    for i, (data, label) in enumerate(self.valid_batches):

  File "anago/reader.py", line 137, in data_generator
    yield preprocessor.transform(X, y)

  File "anago/preprocess.py", line 117, in transform
    y = [[self.vocab_tag[t] for t in sent] for sent in y]

KeyError: 'O'

Tha labels of my entities are like that: "Person", "Location", "Organization". Do I jave to follow the same format as yours?
Are there any hints, on what wrong is happening? Is it because of my dataset or something internal in the system?

Thank you in advance!
Vasiliki

**Comment by sehoi** [comment]
Add the 'O' label to the entities you want to ignore.
At least one 'O' label is in your training datas.

**Comment by OsamaBSalameh** [comment]
I had the same problem too, and I have 'O' labels in my training dataset 

so what is the problem ??

by the way the language I'm working on is Arabic
