### ISSUE TITLE
Error when predict 1-word sentences

### ISSUE THREAD

**Issue by pnvphuong** [Hironsan/anago#55]
I try to run the download_model.py and evaluate with a 1-word sentence
```
Test O
```
However, the model gave the `UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,10] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.`

Would you help me fixing this error? 
Thank you very much

The full trace is below
```
2018-04-25 14:18:39.235184: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-04-25 14:18:39.240128: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-04-25 14:18:39.240182: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: exp
2018-04-25 14:18:39.240204: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: exp
2018-04-25 14:18:39.240255: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.111.0
2018-04-25 14:18:39.240314: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.111.0
2018-04-25 14:18:39.240336: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.111.0
Traceback (most recent call last):
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,10] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
         [[Node: chain_crf_1/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@chain_crf_1/TensorArray"], dtype=DT_FLOAT, element_shape=[?,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"](chain_crf_1/TensorArray, chain_crf_1/TensorArrayStack/range, chain_crf_1/while/Exit_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_model.py", line 18, in <module>
    model.eval(x_test, y_test)
  File "/home/phuongpham/NER/anago/anago/wrapper.py", line 55, in eval
    evaluator.eval(x_test, y_test)
  File "/home/phuongpham/NER/anago/anago/evaluator.py", line 27, in eval
    f1score.on_epoch_end(epoch=-1)  # epoch takes any integer.
  File "/home/phuongpham/NER/anago/anago/metrics.py", line 132, in on_epoch_end
    y_pred = self.model.predict_on_batch(data)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/keras/engine/training.py", line 1945, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2478, in __call__
    **self.session_kwargs)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,10] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
         [[Node: chain_crf_1/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@chain_crf_1/TensorArray"], dtype=DT_FLOAT, element_shape=[?,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"](chain_crf_1/TensorArray, chain_crf_1/TensorArrayStack/range, chain_crf_1/while/Exit_1)]]

Caused by op 'chain_crf_1/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "download_model.py", line 17, in <module>
    model = Sequence.load(dir_path)
  File "/home/phuongpham/NER/anago/anago/wrapper.py", line 77, in load
    self.model = SeqLabeling(config, dummy_embeddings, ntags=len(self.p.vocab_tag))
  File "/home/phuongpham/NER/anago/anago/models.py", line 82, in __init__
    pred = self.crf(x)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/phuongpham/NER/anago/anago/layers.py", line 313, in call
    y_pred = viterbi_decode(x, self.U, self.b_start, self.b_end, mask)
  File "/home/phuongpham/NER/anago/anago/layers.py", line 105, in viterbi_decode
    mask)
  File "/home/phuongpham/NER/anago/anago/layers.py", line 146, in _forward
    last, values, _ = K.rnn(_forward_step, inputs, initial_states)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2772, in rnn
    outputs = output_ta.stack()
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6011, in tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/phuongpham/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,10] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
         [[Node: chain_crf_1/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@chain_crf_1/TensorArray"], dtype=DT_FLOAT, element_shape=[?,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"](chain_crf_1/TensorArray, chain_crf_1/TensorArrayStack/range, chain_crf_1/while/Exit_1)]]
```

**Comment by slouvan** [comment]
@pnvphuong did you find a solution for this?

**Comment by pnvphuong** [comment]
@slouvan no, I just skip all of the 1-word sentences in both training and testing. In fact, the provided dataset in this repository is somehow shorter than the dataset from the original (Theano) repository. I guess all 1-word sentences have been removed. That's only my guess

**Comment by sehoi** [comment]
same issue.
https://github.com/Hironsan/anago/issues/10
